---
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: Update APT cache
      ansible.builtin.package:
        update_cache: true
      when: ansible_distribution == 'Ubuntu'
      become: true

    - name: Install EPEL release repo
      ansible.builtin.yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
        state: present
        disable_gpg_check: true
      when: ansible_os_family == 'RedHat'
      become: true

    - name: DNF Install config-manager
      ansible.builtin.command:
        cmd: "dnf install -y 'dnf-command(config-manager)'"
      when: ansible_os_family == 'RedHat' and ansible_facts['distribution_major_version'] is version('8', '>=')
      become: true

    - name: Enable PowerTools (EL8)
      ansible.builtin.command:
        cmd: "dnf config-manager --set-enabled powertools"
      when: ansible_os_family == 'RedHat' and ansible_facts['distribution_major_version'] == '8'
      become: true

    - name: Enable CRB (EL9+)
      ansible.builtin.command:
        cmd: "dnf config-manager --set-enabled crb"
      when: ansible_os_family == 'RedHat' and ansible_facts['distribution_major_version'] is version('9', '>=')
      become: true
